In [1]:
import fiona
from shapely.geometry import Point, Polygon
import geopandas as gpd
import pandas as pd
import numpy as np
from geopandas import GeoDataFrame

datadir = "../../Data/Data_Frances/"

/Users/carlosmoreno/opt/anaconda3/envs/w210/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

In [2]:
dfall = pd.read_csv(datadir+"df_all.csv")

/var/folders/f3/z2y9_l5x2ddfrpzb4m7jw6_w0000gn/T/ipykernel_39939/818637388.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  dfall = pd.read_csv(datadir+"df_all.csv")

In [3]:
dfall.head()

,Unnamed: 0.1,xg_key,xg_lon_t,xg_lat_t,xg_no_sh,xg_sh,xg_pred,rf_key,rf_lon_t,rf_lat_t,...,Y150,Y200,Y250,Y300,Y500,Y750,Y1000,Y1000plus,Ycoloc,geo_county2
0,0,033_174,-87.624327,30.880381,0.605934,0.394066,0,033_174,-87.624327,30.880381,...,0,0,0,0,0,0,0,101533,0,Escambia
1,1,033_206,-87.618608,30.897536,0.596957,0.403043,0,033_206,-87.618608,30.897536,...,0,0,0,0,0,0,0,101533,0,Escambia
2,2,033_207,-87.618608,30.891818,0.599876,0.400124,0,033_207,-87.618608,30.891818,...,0,0,0,0,0,0,0,101533,0,Escambia
3,3,033_208,-87.618608,30.886099,0.577562,0.422438,0,033_208,-87.618608,30.886099,...,0,0,0,0,0,0,0,101533,0,Escambia
4,4,033_209,-87.618608,30.880381,0.604978,0.395022,0,033_209,-87.618608,30.880381,...,0,0,0,0,0,0,0,101533,0,Escambia

In [5]:
list(dfall.columns)

['Unnamed: 0.1',
 'xg_key',
 'xg_lon_t',
 'xg_lat_t',
 'xg_no_sh',
 'xg_sh',
 'xg_pred',
 'rf_key',
 'rf_lon_t',
 'rf_lat_t',
 'rf_no_sh',
 'rf_sh',
 'rf_pred',
 'lr_key',
 'lr_lon_t',
 'lr_lat_t',
 'lr_no_sh',
 'lr_sh',
 'lr_pred',
 'geo_index',
 'geo_addy',
 'geo_addy_len',
 'geo_zipcode',
 'geo_city',
 'geo_county',
 'geo_key',
 'geo_lat',
 'geo_lon',
 'source',
 'Unnamed: 0',
 'Key',
 'Calcium Carbonate',
 'Gypsum',
 'Soil Health Organic Matter',
 'Percent Clay',
 'Percent Sand',
 'Percent Silt',
 'Available Water Storage',
 'date_ws',
 'name_x',
 'lon_t',
 'lat_t',
 'rolling_7_precip',
 'rolling_15_precip',
 'rolling_30_precip',
 'rolling_60_precip',
 'rolling_90_precip',
 'y1_mean_prc',
 'y1_max_prc',
 'y1_mean_tmp',
 'y1_max_tmp',
 'y1_min_tmp',
 'y2_mean_prc',
 'y2_max_prc',
 'y2_mean_tmp',
 'y2_max_tmp',
 'y2_min_tmp',
 'y3_mean_prc',
 'y3_max_prc',
 'y3_mean_tmp',
 'y3_max_tmp',
 'y3_min_tmp',
 'County',
 'county_fp',
 'name_y',
 'imagenum',
 'geometry',
 'AnnualCrop',
 'Forest',
 'HerbaceousVegetation',
 'Highway',
 'Industrial',
 'Pasture',
 'PermanentCrop',
 'Residential',
 'River',
 'SeaLake',
 'prediction',
 'prediction_name',
 'gridcode',
 'DateD',
 'l25',
 'l50',
 'l75',
 'l100',
 'l150',
 'l200',
 'l250',
 'l300',
 'l500',
 'l750',
 'l1000',
 'l1000plus',
 'coloc',
 'Y25',
 'Y50',
 'Y75',
 'Y100',
 'Y150',
 'Y200',
 'Y250',
 'Y300',
 'Y500',
 'Y750',
 'Y1000',
 'Y1000plus',
 'Ycoloc',
 'geo_county2']

In [26]:
gb1 = dfall.groupby([ 'xg_pred','geo_county','geo_zipcode','prediction_name'])['prediction'].count()

In [27]:
gb1

xg_pred  geo_county      geo_zipcode  prediction_name
0        Alachua County  32044        Forest                    3
                                      HerbaceousVegetation      1
                                      SeaLake                   1
                         32601        Forest                    1
                                      HerbaceousVegetation     10
                                                             ...
1        none            none         Highway                  27
                                      Industrial               45
                                      Residential               4
                                      River                    82
                                      SeaLake                 135
Name: prediction, Length: 8582, dtype: int64

In [28]:
gb1 = gb1.reset_index()
gb1

      xg_pred      geo_county geo_zipcode       prediction_name  prediction
0           0  Alachua County       32044                Forest           3
1           0  Alachua County       32044  HerbaceousVegetation           1
2           0  Alachua County       32044               SeaLake           1
3           0  Alachua County       32601                Forest           1
4           0  Alachua County       32601  HerbaceousVegetation          10
...       ...             ...         ...                   ...         ...
8577        1            none        none               Highway          27
8578        1            none        none            Industrial          45
8579        1            none        none           Residential           4
8580        1            none        none                 River          82
8581        1            none        none               SeaLake         135

[8582 rows x 5 columns]

In [13]:
len(gb1)

1298

In [29]:
gb1.to_csv("datagr/landuse_pred.csv", index=False)